### ISSUE TITLE
javascript error in the main process

### ISSUE THREAD

**Issue by MacgyverJohnson** [mokocup/BetterDiscord-Portable-Installer#1]
Hi there @mokocup 
installed this on latest discord ptb portable by portapps
failed with error(same error as bandagedbd portable installer)  

`
Uncaught Exception:
E:\Downloads\discord-ptb-portable2\BetterDiscord\betterdiscord.asar\injector.js:1
(()=>{"use strict";var e={n:s=>{var n=s&&s.__esModule?()=>s.default:()=>s;return e.d(n,{a:n}),n},d:(s,n)=>{for(var t in n)e.o(n,t)&&!e.o(s,t)&&Object.defineProperty(s,t,{enumerable:!0,get:n[t]})},o:(e,s)=>Object.prototype.hasOwnProperty.call(e,s)};const s=require("path");var n=e.n(s);const t=require("electron");var r=e.n(t);const o=require("module");var i=e.n(o);const a=(e,s)=>{let n;switch(s){case"appPath":n=t.app.getAppPath();break;case"appData":case"userData":case"home":case"cache":case"temp":case"exe":case"module":case"desktop":case"documents":case"downloads":case"music":case"pictures":case"videos":case"recent":case"logs":n=t.app.getPath(s);break;default:n=""}e.returnValue=n},c=()=>{t.app.quit(),t.app.relaunch()},p=async(e,s)=>{try{await e.sender.executeJavaScript(`(() => {try {${s}} catch {}})();`)}catch(e){}},l=e=>e.sender.openDevTools(),d=e=>e.sender.closeDevTools(),u=(e,s,{windowOptions:n,closeOnUrl:r}={})=>new Promise

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:815:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (E:\Downloads\discord-ptb-portable2\app\app-0.0.54\resources\app\index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:880:30)

`
![image](https://user-images.githubusercontent.com/17729946/147387807-e5bed666-9543-44c3-a4c3-dac963d3bb03.png)

Could you please have look at it??

**Comment by mokocup** [comment]
> Hi there @mokocup installed this on latest discord ptb portable by portapps failed with error(same error as bandagedbd portable installer)
> 
> ` Uncaught Exception: E:\Downloads\discord-ptb-portable2\BetterDiscord\betterdiscord.asar\injector.js:1 (()=>{"use strict";var e={n:s=>{var n=s&&s.__esModule?()=>s.default:()=>s;return e.d(n,{a:n}),n},d:(s,n)=>{for(var t in n)e.o(n,t)&&!e.o(s,t)&&Object.defineProperty(s,t,{enumerable:!0,get:n[t]})},o:(e,s)=>Object.prototype.hasOwnProperty.call(e,s)};const s=require("path");var n=e.n(s);const t=require("electron");var r=e.n(t);const o=require("module");var i=e.n(o);const a=(e,s)=>{let n;switch(s){case"appPath":n=t.app.getAppPath();break;case"appData":case"userData":case"home":case"cache":case"temp":case"exe":case"module":case"desktop":case"documents":case"downloads":case"music":case"pictures":case"videos":case"recent":case"logs":n=t.app.getPath(s);break;default:n=""}e.returnValue=n},c=()=>{t.app.quit(),t.app.relaunch()},p=async(e,s)=>{try{await e.sender.executeJavaScript(`(() => {try {${s}} catch {}})();`)}catch(e){}},l=e=>e.sender.openDevTools(),d=e=>e.sender.closeDevTools(),u=(e,s,{windowOptions:n,closeOnUrl:r}={})=>new Promise
> 
> SyntaxError: Unexpected token '.' at Module._compile (internal/modules/cjs/loader.js:815:22) at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10) at Module.load (internal/modules/cjs/loader.js:735:32) at Module._load (internal/modules/cjs/loader.js:648:12) at Module._load (electron/js2c/asar.js:717:26) at Function.Module._load (electron/js2c/asar.js:717:26) at Module.require (internal/modules/cjs/loader.js:775:19) at require (internal/modules/cjs/helpers.js:68:18) at Object. (E:\Downloads\discord-ptb-portable2\app\app-0.0.54\resources\app\index.js:1:1) at Module._compile (internal/modules/cjs/loader.js:880:30)
> 
> ` ![image](https://user-images.githubusercontent.com/17729946/147387807-e5bed666-9543-44c3-a4c3-dac963d3bb03.png)
> 
> Could you please have look at it??

Look like its the error come from BD itself
Maybe its the Discord PTB version ? 

Can you try uninstall and reinstall again ?

Discord PTB Portable 1.0.1010-17
Installer 1.2.0

**Comment by mokocup** [comment]
@MacgyverJohnson Please create new issues if u havent resolved this
